package com.parswha.createchemworks.client.Elements;

import java.util.List;

public final class ElementsData {
    public static final int PERIODS = 9;
    public static final int MAIN_COLUMNS = 19;

    // Intentionally hardcoded while the extended chemistry design is in flux.
    private static final List<Element> ELEMENTS = List.of(
        e(1, "H", "Hydrogen", 1, 0, ElectronBlock.S),
        e(2, "He", "Helium", 1, 18, ElectronBlock.S),
        e(3, "Li", "Lithium", 2, 0, ElectronBlock.S),
        e(4, "Be", "Beryllium", 2, 1, ElectronBlock.S),
        e(5, "B", "Boron", 2, 13, ElectronBlock.P),
        e(6, "C", "Carbon", 2, 14, ElectronBlock.P),
        e(7, "N", "Nitrogen", 2, 15, ElectronBlock.P),
        e(8, "O", "Oxygen", 2, 16, ElectronBlock.P),
        e(9, "F", "Fluorine", 2, 17, ElectronBlock.P),
        e(10, "Ne", "Neon", 2, 18, ElectronBlock.P),
        e(11, "Na", "Sodium", 3, 0, ElectronBlock.S),
        e(12, "Mg", "Magnesium", 3, 1, ElectronBlock.S),
        e(13, "Al", "Aluminium", 3, 13, ElectronBlock.P),
        e(14, "Si", "Silicon", 3, 14, ElectronBlock.P),
        e(15, "P", "Phosphorus", 3, 15, ElectronBlock.P),
        e(16, "S", "Sulfur", 3, 16, ElectronBlock.P),
        e(17, "Cl", "Chlorine", 3, 17, ElectronBlock.P),
        e(18, "Ar", "Argon", 3, 18, ElectronBlock.P),
        e(19, "K", "Potassium", 4, 0, ElectronBlock.S),
        e(20, "Ca", "Calcium", 4, 1, ElectronBlock.S),
        e(21, "Sc", "Scandium", 4, 3, ElectronBlock.D),
        e(22, "Ti", "Titanium", 4, 4, ElectronBlock.D),
        e(23, "V", "Vanadium", 4, 5, ElectronBlock.D),
        e(24, "Cr", "Chromium", 4, 6, ElectronBlock.D),
        e(25, "Mn", "Manganese", 4, 7, ElectronBlock.D),
        e(26, "Fe", "Iron", 4, 8, ElectronBlock.D),
        e(27, "Co", "Cobalt", 4, 9, ElectronBlock.D),
        e(28, "Ni", "Nickel", 4, 10, ElectronBlock.D),
        e(29, "Cu", "Copper", 4, 11, ElectronBlock.D),
        e(30, "Zn", "Zinc", 4, 12, ElectronBlock.D),
        e(31, "Ga", "Gallium", 4, 13, ElectronBlock.P),
        e(32, "Ge", "Germanium", 4, 14, ElectronBlock.P),
        e(33, "As", "Arsenic", 4, 15, ElectronBlock.P),
        e(34, "Se", "Selenium", 4, 16, ElectronBlock.P),
        e(35, "Br", "Bromine", 4, 17, ElectronBlock.P),
        e(36, "Kr", "Krypton", 4, 18, ElectronBlock.P),
        e(37, "Rb", "Rubidium", 5, 0, ElectronBlock.S),
        e(38, "Sr", "Strontium", 5, 1, ElectronBlock.S),
        e(39, "Y", "Yttrium", 5, 3, ElectronBlock.D),
        e(40, "Zr", "Zirconium", 5, 4, ElectronBlock.D),
        e(41, "Nb", "Niobium", 5, 5, ElectronBlock.D),
        e(42, "Mo", "Molybdenum", 5, 6, ElectronBlock.D),
        e(43, "Tc", "Technetium", 5, 7, ElectronBlock.D),
        e(44, "Ru", "Ruthenium", 5, 8, ElectronBlock.D),
        e(45, "Rh", "Rhodium", 5, 9, ElectronBlock.D),
        e(46, "Pd", "Palladium", 5, 10, ElectronBlock.D),
        e(47, "Ag", "Silver", 5, 11, ElectronBlock.D),
        e(48, "Cd", "Cadmium", 5, 12, ElectronBlock.D),
        e(49, "In", "Indium", 5, 13, ElectronBlock.P),
        e(50, "Sn", "Tin", 5, 14, ElectronBlock.P),
        e(51, "Sb", "Antimony", 5, 15, ElectronBlock.P),
        e(52, "Te", "Tellurium", 5, 16, ElectronBlock.P),
        e(53, "I", "Iodine", 5, 17, ElectronBlock.P),
        e(54, "Xe", "Xenon", 5, 18, ElectronBlock.P),
        e(55, "Cs", "Caesium", 6, 0, ElectronBlock.S),
        e(56, "Ba", "Barium", 6, 1, ElectronBlock.S),
        e(57, "La", "Lanthanum", 6, 0, ElectronBlock.F),
        e(58, "Ce", "Cerium", 6, 1, ElectronBlock.F),
        e(59, "Pr", "Praseodymium", 6, 2, ElectronBlock.F),
        e(60, "Nd", "Neodymium", 6, 3, ElectronBlock.F),
        e(61, "Pm", "Promethium", 6, 4, ElectronBlock.F),
        e(62, "Sm", "Samarium", 6, 5, ElectronBlock.F),
        e(63, "Eu", "Europium", 6, 6, ElectronBlock.F),
        e(64, "Gd", "Gadolinium", 6, 7, ElectronBlock.F),
        e(65, "Tb", "Terbium", 6, 8, ElectronBlock.F),
        e(66, "Dy", "Dysprosium", 6, 9, ElectronBlock.F),
        e(67, "Ho", "Holmium", 6, 10, ElectronBlock.F),
        e(68, "Er", "Erbium", 6, 11, ElectronBlock.F),
        e(69, "Tm", "Thulium", 6, 12, ElectronBlock.F),
        e(70, "Yb", "Ytterbium", 6, 13, ElectronBlock.F),
        e(71, "Lu", "Lutetium", 6, 3, ElectronBlock.D),
        e(72, "Hf", "Hafnium", 6, 4, ElectronBlock.D),
        e(73, "Ta", "Tantalum", 6, 5, ElectronBlock.D),
        e(74, "W", "Tungsten", 6, 6, ElectronBlock.D),
        e(75, "Re", "Rhenium", 6, 7, ElectronBlock.D),
        e(76, "Os", "Osmium", 6, 8, ElectronBlock.D),
        e(77, "Ir", "Iridium", 6, 9, ElectronBlock.D),
        e(78, "Pt", "Platinum", 6, 10, ElectronBlock.D),
        e(79, "Au", "Gold", 6, 11, ElectronBlock.D),
        e(80, "Hg", "Mercury", 6, 12, ElectronBlock.D),
        e(81, "Tl", "Thallium", 6, 13, ElectronBlock.P),
        e(82, "Pb", "Lead", 6, 14, ElectronBlock.P),
        e(83, "Bi", "Bismuth", 6, 15, ElectronBlock.P),
        e(84, "Po", "Polonium", 6, 16, ElectronBlock.P),
        e(85, "At", "Astatine", 6, 17, ElectronBlock.P),
        e(86, "Rn", "Radon", 6, 18, ElectronBlock.P),
        e(87, "Fr", "Francium", 7, 0, ElectronBlock.S),
        e(88, "Ra", "Radium", 7, 1, ElectronBlock.S),
        e(89, "Ac", "Actinium", 7, 0, ElectronBlock.F),
        e(90, "Th", "Thorium", 7, 1, ElectronBlock.F),
        e(91, "Pa", "Protactinium", 7, 2, ElectronBlock.F),
        e(92, "U", "Uranium", 7, 3, ElectronBlock.F),
        e(93, "Np", "Neptunium", 7, 4, ElectronBlock.F),
        e(94, "Pu", "Plutonium", 7, 5, ElectronBlock.F),
        e(95, "Am", "Americium", 7, 6, ElectronBlock.F),
        e(96, "Cm", "Curium", 7, 7, ElectronBlock.F),
        e(97, "Bk", "Berkelium", 7, 8, ElectronBlock.F),
        e(98, "Cf", "Californium", 7, 9, ElectronBlock.F),
        e(99, "Es", "Einsteinium", 7, 10, ElectronBlock.F),
        e(100, "Fm", "Fermium", 7, 11, ElectronBlock.F),
        e(101, "Md", "Mendelevium", 7, 12, ElectronBlock.F),
        e(102, "No", "Nobelium", 7, 13, ElectronBlock.F),
        e(103, "Lr", "Lawrencium", 7, 3, ElectronBlock.D),
        e(104, "Rf", "Rutherfordium", 7, 4, ElectronBlock.D),
        e(105, "Db", "Dubnium", 7, 5, ElectronBlock.D),
        e(106, "Sg", "Seaborgium", 7, 6, ElectronBlock.D),
        e(107, "Bh", "Bohrium", 7, 7, ElectronBlock.D),
        e(108, "Hs", "Hassium", 7, 8, ElectronBlock.D),
        e(109, "Mt", "Meitnerium", 7, 9, ElectronBlock.D),
        e(110, "Ds", "Darmstadtium", 7, 10, ElectronBlock.D),
        e(111, "Rg", "Roentgenium", 7, 11, ElectronBlock.D),
        e(112, "Cn", "Copernicium", 7, 12, ElectronBlock.D),
        e(113, "Nh", "Nihonium", 7, 13, ElectronBlock.P),
        e(114, "Fl", "Flerovium", 7, 14, ElectronBlock.P),
        e(115, "Mc", "Moscovium", 7, 15, ElectronBlock.P),
        e(116, "Lv", "Livermorium", 7, 16, ElectronBlock.P),
        e(117, "Ts", "Tennessine", 7, 17, ElectronBlock.P),
        e(118, "Og", "Oganesson", 7, 18, ElectronBlock.P),
        e(119, "An", "Ancientium", 8, 0, ElectronBlock.S),
        e(120, "Aa", "Catalyrium", 8, 1, ElectronBlock.S),
        e(121, "Ab", "Resonarium", 8, 0, ElectronBlock.T),
        e(122, "Ad", "Voltrium", 8, 1, ElectronBlock.T),
        e(123, "Ae", "Synthium", 8, 2, ElectronBlock.T),
        e(124, "Af", "Adaptium", 8, 3, ElectronBlock.T),
        e(125, "Ah", "Unifornium", 8, 4, ElectronBlock.T),
        e(126, "Ai", "Terralium", 8, 5, ElectronBlock.T),
        e(127, "Aj", "Lunarium", 8, 6, ElectronBlock.T),
        e(128, "Ak", "Levitium", 8, 7, ElectronBlock.T),
        e(129, "Ao", "Pyronium", 8, 8, ElectronBlock.T),
        e(130, "Ap", "Aresium", 8, 9, ElectronBlock.T),
        e(131, "Aq", "Harmonium", 8, 10, ElectronBlock.T),
        e(132, "Av", "Gyrium", 8, 11, ElectronBlock.T),
        e(133, "Aw", "Sonorium", 8, 12, ElectronBlock.T),
        e(134, "Ax", "Fluxium", 8, 13, ElectronBlock.T),
        e(135, "Ay", "Quantium", 8, 14, ElectronBlock.T),
        e(136, "Az", "Metastium", 8, 15, ElectronBlock.T),
        e(137, "Bb", "Phasium", 8, 16, ElectronBlock.T),
        e(138, "Bc", "Anomalium", 8, 17, ElectronBlock.T),
        e(139, "Bd", "Octavafissium", 8, 0, ElectronBlock.F),
        e(140, "Bf", "Octavaradioium", 8, 1, ElectronBlock.F),
        e(141, "Bg", "Octavaactinium", 8, 2, ElectronBlock.F),
        e(142, "Bj", "Octavanucleoium", 8, 3, ElectronBlock.F),
        e(143, "Bl", "Octavadecayium", 8, 4, ElectronBlock.F),
        e(144, "Bm", "Octavafusionium", 8, 5, ElectronBlock.F),
        e(145, "Bn", "Octavafissbium", 8, 6, ElectronBlock.F),
        e(146, "Bo", "Octavaradiobium", 8, 7, ElectronBlock.F),
        e(147, "Bp", "Octavaactinbium", 8, 8, ElectronBlock.F),
        e(148, "Bq", "Octavanucleobium", 8, 9, ElectronBlock.F),
        e(149, "Bs", "Octavadecaybium", 8, 10, ElectronBlock.F),
        e(150, "Bt", "Octavafusionbium", 8, 11, ElectronBlock.F),
        e(151, "Bu", "Octavafisscium", 8, 12, ElectronBlock.F),
        e(152, "Bv", "Octavaradiocium", 8, 13, ElectronBlock.F),
        e(153, "Bw", "Octavaferroium", 8, 3, ElectronBlock.D),
        e(154, "Bx", "Octavacatalium", 8, 4, ElectronBlock.D),
        e(155, "By", "Octavaconductium", 8, 5, ElectronBlock.D),
        e(156, "Bz", "Octavachromium", 8, 6, ElectronBlock.D),
        e(157, "Cb", "Octavakinetium", 8, 7, ElectronBlock.D),
        e(158, "Cc", "Octavaallotropium", 8, 8, ElectronBlock.D),
        e(159, "Cg", "Octavaferrobium", 8, 9, ElectronBlock.D),
        e(160, "Ch", "Octavacatalbium", 8, 10, ElectronBlock.D),
        e(161, "Ci", "Octavaconductbium", 8, 11, ElectronBlock.D),
        e(162, "Cj", "Octavachrombium", 8, 12, ElectronBlock.D),
        e(163, "Ck", "Octavaaerium", 8, 13, ElectronBlock.P),
        e(164, "Cp", "Octavacrystium", 8, 14, ElectronBlock.P),
        e(165, "Cq", "Octavaluminium", 8, 15, ElectronBlock.P),
        e(166, "Ct", "Octavareactium", 8, 16, ElectronBlock.P),
        e(167, "Cv", "Octavaplasmium", 8, 17, ElectronBlock.P),
        e(168, "Cw", "Octavavaporium", 8, 18, ElectronBlock.P),
        e(169, "Cx", "Enneasolium", 9, 0, ElectronBlock.S),
        e(170, "Cy", "Enneaalkium", 9, 1, ElectronBlock.S),
        e(171, "Cz", "Enneaharmonium", 9, 0, ElectronBlock.T),
        e(172, "Da", "Ennearesonium", 9, 1, ElectronBlock.T),
        e(173, "Dc", "Enneagyroium", 9, 2, ElectronBlock.T),
        e(174, "Dd", "Enneasonorium", 9, 3, ElectronBlock.T),
        e(175, "De", "Ennearotarium", 9, 4, ElectronBlock.T),
        e(176, "Df", "Enneaphonoium", 9, 5, ElectronBlock.T),
        e(177, "Dg", "Enneaharmonbium", 9, 6, ElectronBlock.T),
        e(178, "Dh", "Ennearesonbium", 9, 7, ElectronBlock.T),
        e(179, "Di", "Enneagyrobium", 9, 8, ElectronBlock.T),
        e(180, "Dj", "Enneasonorbium", 9, 9, ElectronBlock.T),
        e(181, "Dk", "Ennearotarbium", 9, 10, ElectronBlock.T),
        e(182, "Dl", "Enneaphonobium", 9, 11, ElectronBlock.T),
        e(183, "Dm", "Enneaharmoncium", 9, 12, ElectronBlock.T),
        e(184, "Dn", "Ennearesoncium", 9, 13, ElectronBlock.T),
        e(185, "Do", "Enneagyrocium", 9, 14, ElectronBlock.T),
        e(186, "Dp", "Enneasonorcium", 9, 15, ElectronBlock.T),
        e(187, "Dq", "Ennearotarcium", 9, 16, ElectronBlock.T),
        e(188, "Dr", "Enneaphonocium", 9, 17, ElectronBlock.T),
        e(189, "Dt", "Enneafissium", 9, 0, ElectronBlock.F),
        e(190, "Du", "Ennearadioium", 9, 1, ElectronBlock.F),
        e(191, "Dv", "Enneaactinium", 9, 2, ElectronBlock.F),
        e(192, "Dw", "Enneanucleoium", 9, 3, ElectronBlock.F),
        e(193, "Dx", "Enneadecayium", 9, 4, ElectronBlock.F),
        e(194, "Dz", "Enneafusionium", 9, 5, ElectronBlock.F),
        e(195, "Ea", "Enneafissbium", 9, 6, ElectronBlock.F),
        e(196, "Eb", "Ennearadiobium", 9, 7, ElectronBlock.F),
        e(197, "Ec", "Enneaactinbium", 9, 8, ElectronBlock.F),
        e(198, "Ed", "Enneanucleobium", 9, 9, ElectronBlock.F),
        e(199, "Ee", "Enneadecaybium", 9, 10, ElectronBlock.F),
        e(200, "Ef", "Enneafusionbium", 9, 11, ElectronBlock.F),
        e(201, "Eg", "Enneafisscium", 9, 12, ElectronBlock.F),
        e(202, "Eh", "Ennearadiocium", 9, 13, ElectronBlock.F),
        e(203, "Ei", "Enneaferroium", 9, 3, ElectronBlock.D),
        e(204, "Ej", "Enneacatalium", 9, 4, ElectronBlock.D),
        e(205, "Ek", "Enneaconductium", 9, 5, ElectronBlock.D),
        e(206, "El", "Enneachromium", 9, 6, ElectronBlock.D),
        e(207, "Em", "Enneakinetium", 9, 7, ElectronBlock.D),
        e(208, "En", "Enneaallotropium", 9, 8, ElectronBlock.D),
        e(209, "Eo", "Enneaferrobium", 9, 9, ElectronBlock.D),
        e(210, "Ep", "Enneacatalbium", 9, 10, ElectronBlock.D),
        e(211, "Eq", "Enneaconductbium", 9, 11, ElectronBlock.D),
        e(212, "Et", "Enneachrombium", 9, 12, ElectronBlock.D),
        e(213, "Ev", "Enneaaerium", 9, 13, ElectronBlock.P),
        e(214, "Ew", "Enneacrystium", 9, 14, ElectronBlock.P),
        e(215, "Ex", "Ennealuminium", 9, 15, ElectronBlock.P),
        e(216, "Ey", "Enneareactium", 9, 16, ElectronBlock.P),
        e(217, "Ez", "Enneaplasmium", 9, 17, ElectronBlock.P),
        e(218, "Fa", "Enneavaporium", 9, 18, ElectronBlock.P)
    );

    private ElementsData() {}

    public static List<Element> all() { return ELEMENTS; }

    public static List<Element> mainTableElements() {
        return ELEMENTS.stream().filter(Element::belongsOnMainTable).toList();
    }

    public static List<Element> elementsIn(ElectronBlock block) {
        return ELEMENTS.stream().filter(element -> element.block() == block).toList();
    }

    private static Element e(int number, String symbol, String name, int period,
                             int column, ElectronBlock block) {
        return new Element(number, symbol, name, period, column, block);
    }
}
